services:
  symfony:
    build:
      dockerfile: ./Dockerfile-${APP_ENV}
      args:
        PHP_VERSION: ${PHP_VERSION}
    ports:
      - 8000:8000
    depends_on:
      - mysql
    # restart: always Relou pour les tests

  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${DATABASE_ROOT_PASSWORD}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - db-data:/var/lib/mysql
    # restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    depends_on:
      - mysql

volumes:
  db-data:
